name: CD
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: '*'
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [8,9,10]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 15.x
      uses: actions/setup-node@main
      with:
        node-version: 15
        check-latest: true
    - name: Environment - Apt
      run : |
        sudo apt-get install --allow-unauthenticated -y apt-transport-https && sudo apt-get update
        sudo apt-get install --allow-unauthenticated -y --install-recommends gcc-multilib g++-multilib rpm libarchive-tools jq rsync
    - uses: actions/checkout@main
      with:
        submodules: 'true'
    - name: Set up JDK ${{ matrix.node-version }}
      uses: actions/setup-java@main
      with:
        java-version: ${{ matrix.node-version }}
    - name: Build
      shell: bash
      run: |
        PROJECTROOTPATH=$PWD
        export PRP=${PROJECTROOTPATH}

        CI=false scripts/build.sh --linux && \
        cd ${PRP}/bootui/tachiweb-bootstrap && bash -c "cd bootui/tachiweb-bootstrap && bash ../../scripts/buildWindowsInDocker.sh"
        cd ${PRP}/bootui/tachiweb-bootstrap/dist/ && zip -r TachiWeb-win32-portable.zip win-ia32-unpacked
        cd ${PRP}/bootui/tachiweb-bootstrap/dist/ && zip -r TachiWeb-win64-portable.zip win-unpacked
        # bash -c 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc'
        # bash -c 'NODE_ENV="development" scripts/updateApiClients.sh'
        ls -1 bootui/tachiweb-bootstrap/dist/                   | grep -i tachiweb
        ls -1 bootui/tachiweb-bootstrap/dist/squirrel-windows/  | grep -i tachiweb
